language: bash
services: docker
before_install:
  - cd RestWithSpringBootUdemy\ Docker/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$`{DOCKER_PASSWORD}" | docker login --user "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push igorfersantos/mysql-rest-with-spring-boot-udemy;
    docker push igorfersantos/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false
    